"""empty message

Revision ID: 009928a661ae
Revises: 
Create Date: 2022-03-27 15:59:54.269422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '009928a661ae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genre',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_genre_name'), 'genre', ['name'], unique=True)
    op.create_table('producer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('poster', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_producer_name'), 'producer', ['name'], unique=True)
    op.create_table('star',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Значение', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Значение')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('poster', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_name'), 'user', ['name'], unique=True)
    op.create_table('rating',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('star', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['star'], ['star.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('slug', sa.String(length=150), nullable=True),
    sa.Column('genres_id', sa.Integer(), nullable=True),
    sa.Column('release_date', sa.DateTime(), nullable=True),
    sa.Column('producer_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.Text(length=500), nullable=True),
    sa.Column('rating_id', sa.Integer(), nullable=True),
    sa.Column('poster', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('publication', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['genres_id'], ['genre.id'], ),
    sa.ForeignKeyConstraint(['producer_id'], ['producer.id'], ),
    sa.ForeignKeyConstraint(['rating_id'], ['rating.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movie_publication'), 'movie', ['publication'], unique=False)
    op.create_index(op.f('ix_movie_release_date'), 'movie', ['release_date'], unique=False)
    op.create_index(op.f('ix_movie_slug'), 'movie', ['slug'], unique=True)
    op.create_table('movie_genre',
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.Column('genre_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.id'], ),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], )
    )
    op.create_table('movie_rating',
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.Column('rating_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], ),
    sa.ForeignKeyConstraint(['rating_id'], ['rating.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movie_rating')
    op.drop_table('movie_genre')
    op.drop_index(op.f('ix_movie_slug'), table_name='movie')
    op.drop_index(op.f('ix_movie_release_date'), table_name='movie')
    op.drop_index(op.f('ix_movie_publication'), table_name='movie')
    op.drop_table('movie')
    op.drop_table('rating')
    op.drop_index(op.f('ix_user_name'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('star')
    op.drop_index(op.f('ix_producer_name'), table_name='producer')
    op.drop_table('producer')
    op.drop_index(op.f('ix_genre_name'), table_name='genre')
    op.drop_table('genre')
    # ### end Alembic commands ###
