"""empty message

Revision ID: 1a2aa0517f08
Revises: ee41d5535345
Create Date: 2022-03-17 12:35:42.017762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a2aa0517f08'
down_revision = 'ee41d5535345'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('genre', sa.Column('poster', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('genre', 'poster')
    # ### end Alembic commands ###
