"""empty message

Revision ID: 423ff276befb
Revises: d89ec63fe553
Create Date: 2022-03-24 17:17:58.169506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '423ff276befb'
down_revision = 'd89ec63fe553'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'movie', type_='foreignkey')
    op.drop_column('movie', 'genres_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('genres_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'movie', 'genre', ['genres_id'], ['id'])
    # ### end Alembic commands ###
