"""empty message

Revision ID: ee41d5535345
Revises: e2fc07d3b011
Create Date: 2022-03-14 13:07:46.866139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee41d5535345'
down_revision = 'e2fc07d3b011'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('slug', sa.String(length=150), nullable=True))
    op.create_index(op.f('ix_movie_slug'), 'movie', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movie_slug'), table_name='movie')
    op.drop_column('movie', 'slug')
    # ### end Alembic commands ###
